import { ApplicationConfig, mergeApplicationConfig } from '@angular/core';
import { RenderMode, ServerRoute, provideServerRendering, withRoutes } from '@angular/ssr';
import { appConfig } from './app.config';

const imageToolServerRoutes: ServerRoute[] = [
  'rotate-image',
  'flip-image',
  'watermark-image',
  'webp-to-jpg',
  'webp-to-png',
  'jpg-to-avif',
  'avif-to-jpg',
  'heic-to-jpg',
  'gif-to-png',
  'convert-to-ico',
  'svg-to-png',
  'image-metadata-viewer',
  'image-dpi-checker',
  'change-image-dpi',
  'image-size-checker',
  'color-picker-from-image',
  'blur-image',
  'sharpen-image',
  'brightness-contrast',
  'grayscale-filter',
  'sepia-filter',
  'invert-colors',
  'image-to-base64',
  'base64-to-image',
].map((path) => ({ path, renderMode: RenderMode.Prerender }));

const textToolServerRoutes: ServerRoute[] = [
  'word-counter',
  'character-counter',
  'text-compare',
  'text-repeater',
  'random-text-generator',
  'remove-duplicate-lines',
  'remove-empty-lines',
  'remove-extra-spaces',
  'sort-lines',
  'reverse-text',
  'case-converter',
  'slug-generator',
].map((path) => ({ path, renderMode: RenderMode.Prerender }));

const seoToolServerRoutes: ServerRoute[] = [
  'meta-tag-generator',
  'robots-txt-generator',
  'sitemap-generator',
  'canonical-tag-generator',
  'open-graph-generator',
  'twitter-card-generator',
  'faq-schema-generator',
  'breadcrumb-schema-generator',
  'organization-schema-generator',
  'product-schema-generator',
  'article-schema-generator',
  'json-ld-generator',
  'hreflang-generator',
].map((path) => ({ path, renderMode: RenderMode.Prerender }));

const utilityToolServerRoutes: ServerRoute[] = [
  'json-formatter',
  'json-validator',
  'xml-formatter',
  'xml-validator',
  'html-formatter',
  'css-formatter',
  'javascript-formatter',
  'html-minifier',
  'css-minifier',
  'javascript-minifier',
  'sql-formatter',
  'url-encode',
  'url-decode',
  'base64-encode',
  'base64-decode',
  'jwt-decoder',
  'uuid-generator',
  'md5-generator',
  'sha1-generator',
  'sha256-generator',
  'sha512-generator',
  'age-calculator',
  'bmi-calculator',
  'percentage-calculator',
  'discount-calculator',
  'gst-calculator',
  'vat-calculator',
  'emi-calculator',
  'unit-converter',
  'scientific-calculator',
  'binary-calculator',
  'qr-code-generator',
  'barcode-generator',
  'password-generator',
  'lorem-ipsum-generator',
  'random-number-generator',
  'random-name-generator',
  'random-color-generator',
  'css-gradient-generator',
  'css-box-shadow-generator',
  'css-border-radius-generator',
  'css-clip-path-generator',
  'merge-pdf',
  'split-pdf',
  'rotate-pdf',
  'extract-pdf-pages',
  'rearrange-pdf-pages',
  'delete-pdf-pages',
  'add-page-numbers',
  'pdf-to-images',
  'pdf-metadata-viewer',
  'kml-circle-generator',
  'kml-polygon-generator',
  'geojson-to-kml',
  'kml-to-geojson',
  'gpx-to-kml',
  'coordinate-converter',
  'latitude-longitude-finder',
  'distance-calculator',
  'area-calculator',
  'buffer-generator',
  'hex-to-rgb',
  'rgb-to-hex',
  'hex-to-hsl',
  'hsl-to-hex',
  'color-palette-generator',
  'gradient-generator',
  'contrast-checker',
  'color-picker',
  'timestamp-converter',
  'unix-timestamp-converter',
  'time-zone-converter',
  'date-difference-calculator',
  'countdown-timer',
].map((path) => ({ path, renderMode: RenderMode.Prerender }));

const serverRoutes: ServerRoute[] = [
  { path: '', renderMode: RenderMode.Prerender },
  { path: 'blog', renderMode: RenderMode.Prerender },
  { path: 'blog/:slug', renderMode: RenderMode.Client },
  { path: 'compress', renderMode: RenderMode.Prerender },
  { path: 'convert-webp', renderMode: RenderMode.Prerender },
  { path: 'resize', renderMode: RenderMode.Prerender },
  { path: 'jpg-to-png', renderMode: RenderMode.Prerender },
  { path: 'png-to-svg', renderMode: RenderMode.Prerender },
  { path: 'images-to-pdf', renderMode: RenderMode.Prerender },
  ...imageToolServerRoutes,
  ...textToolServerRoutes,
  ...seoToolServerRoutes,
  ...utilityToolServerRoutes,
  { path: 'privacy-policy', renderMode: RenderMode.Prerender },
  { path: 'terms-of-service', renderMode: RenderMode.Prerender },
  { path: 'contact', renderMode: RenderMode.Prerender },
  { path: 'share/:id', renderMode: RenderMode.Client },
  { path: '**', renderMode: RenderMode.Client },
];

const serverConfig: ApplicationConfig = {
  providers: [provideServerRendering(withRoutes(serverRoutes))],
};

export const config = mergeApplicationConfig(appConfig, serverConfig);
